### ISSUE TITLE
Facing an error while running Rson vs Jsonski benchmark

### ISSUE THREAD

**Issue by gandharva26** [V0ldek/rsonpath#30]
**Describe the bug**

I am trying to run rson vs jsonski benchmark facing this error where I am unable to debug since I am not experienced with Rust. I have attached the image.

**Proposed solution (optional)**
Idea on an appropriate fix.

**Desktop (please complete the following information):**
- MacOS - i9
 - rustc 1.64.0 (a55dd71d5 2022-09-19)

**Additional context**
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/55717003/194966080-0ca3c15e-237d-4992-87a3-6b365a2ac8a3.png">

**Comment by V0ldek** [comment]
Hey @gandharva26 

You should run benches with the following command ran from the root directory of the project:

```bash
cargo bench --bench <name>
```

So in your case you'd navigate to `/Users/gandharvadeshpande/Workplace/rsonpath` and run

```bash
cargo bench --bench rsonpath_vs_jsonski
```

Please tell me if this works :)

**Comment by gandharva26** [comment]
Thanks! It worked, i was probably running the wrong command.

**Comment by V0ldek** [comment]
I'll close this issue but follow up on it here to make dev experience a bit better:  #32

Thanks for reporting!

**Comment by V0ldek** [comment]
Changed in #4, now running the bench as in the issue results in the following error:

![image](https://user-images.githubusercontent.com/20441980/201228069-970d00ce-ccc7-4664-8839-0d7cdc006bfb.png)
