### ISSUE TITLE
Bug (panic) parsing incorrect Json

### ISSUE THREAD

**Issue by charles-paperman** [V0ldek/rsonpath#31]
**Describe the bug**
panic message when reading incorrect value. 

```
The application panicked (crashed).
Message:  index out of bounds: the len is 128 but the index is 18446744073709551615
Location: /home/cha/git/rust/rsonpath/rsonpath/src/stackless.rs:297
``

**MRE**
Example of incorrectly formatted document:

{'a': {'b': 'c', 'e': 'f'}, 'g': 'h'}

(Python dict not Jsonified)

**Expected behavior**
If the formatting error is detectable, throw an incorrect input error.

**Comment by V0ldek** [comment]
After #13 , we should strive to make the crate panic-free &ndash; remove `unwrap` and `expect` calls and use normal Errors for that. There are lints that can enforce panicless code in `clippy`. I'll create a larger issue for this.

**Comment by V0ldek** [comment]
This will be handled in #39. Leaving the issue open until then to confirm that the given example will have been fixed.
